name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '12'
        cache: 'yarn'
    - run: rm -rf node_modules && yarn install --frozen-lockfile
    - run: yarn run build
    - run: yarn test
